var names = [
  // HTMLFormElement
  "elements","length", //readonly.
  "name", "acceptCharset", "action", "enctype", "method", "target", "submit", "reset",
  
  // HTMLElement
  "id", "title", "lang", "dir", "className",
  
  // Element.
  "tagName", "schemaTypeInfo", // readonly.
  "getAttribute", "removeAttribute", "getAttributeNode",
  "setAttributeNode", "removeAttributeNode", "getElementsByTagName",
  "getAttributeNS", "setAttributeNS", "removeAttributeNS",
  "getAttributeNodeNS", "setAttributeNodeNS", "getElementsByTagNameNS",
  "hasAttribute", "hasAttributeNS", "setIdAttribute", "setIdAttributeNS",
  "setIdAttributeNode",
  
  // Node.
  // Node constants.
  "ELEMENT_NODE",
  "ATTRIBUTE_NODE",
  "TEXT_NODE",
  "CDATA_SECTION_NODE",
  "ENTITY_REFERENCE_NODE",
  "ENTITY_NODE",
  "PROCESSING_INSTRUCTION_NODE",
  "COMMENT_NODE",
  "DOCUMENT_NODE",
  "DOCUMENT_TYPE_NODE",
  "DOCUMENT_FRAGMENT_NODE",
  "NOTATION_NODE",
  "DOCUMENT_POSITION_DISCONNECTED",
  "DOCUMENT_POSITION_PRECEDING",
  "DOCUMENT_POSITION_FOLLOWING",
  "DOCUMENT_POSITION_CONTAINS",
  "DOCUMENT_POSITION_CONTAINED_BY",
  "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
  
  // Readonly.
  "nodeName",
  "nodeType",
  "parentNode",
  "childNodes",
  "firstChild",
  "lastChild",
  "previousSibling",
  "nextSibling",
  "attributes",
  "ownerDocument",
  "namespaceURI",
  "localName",
  "baseURI",
  
  "nodeValue",
  "insertBefore",
  "replaceChild",
  "removeChild",
  "appendChild",
  "hasChildNodes",
  "cloneNode",
  "normalize",
  "isSupported",
  "prefix",
  "hasAttributes",
  "compareDocumentPosition",
  "textContent",
  "isSameNode",
  "lookupPrefix",
  "isDefaultNamespaceURI",
  "isEqualNode",
  "getFeature",
  "setUserData",
  "getUserData",
  
  // ElementCSSInlineStyle.
  "style", // readonly.
  
  // EventTarget.
  "addEventListener", 
  "removeEventListener",
  "dispatchEvent",
  
  // Mouse Events
  "onclick",
  "onmousedown",
  "onmouseup",
  "onmouseover",
  "onmousemove",
  "onmouseout",
  "ondblclick",
  
  // MouseWheelEvent.
  "onmousewheel",
  "onmousemultiwheel",
  
  // Key Events.
  "onkeydown",
  "onkeyup",
  "onkeypress",
  
  // bubbled events?
  "onchage",
  "onabort",
  "onerror",
  "onselect",
  "onresize",
  "onscroll",
  
  // New Events for Element:
  "onfocus",
  "onblur",
  
  // Proprietary MSIE (also HTML 5/FF).
  "clientHeight",
  "clientWidth",
  "offsetHeight",
  "offsetWidth",
  "clientLeft",
  "clientTop",
  "contentEditable",
  "getBoundingClientRect",
  "getClientRects",
  "getElementsByClassName",
  "scrollIntoView",
  "scrollLeft",
  "scrollTop",
  "scrollWidth",
  "scrollHeight",
  "tabIndex",
  "encoding", 
  "spellcheck",
  "innerHTML",
  "innerText",
  "children",
  
  "ariaBusy",
  "ariaChecked",
  "ariaControls",
  "ariaDescribability",
  "ariaDisabled",
  "ariaExpanded",
  "ariaFlowto",
  "ariaHaspopup",
  "ariaHidden",
  "ariaInvalid",
  "ariaLabelledby",
  "ariaLevel",
  "ariaMultiselect",
  "ariaOwns",
  "ariaPosinset",
  "ariaPressed",
  "ariaReadonly",
  "ariaRequired",
  "ariaSecret",
  "ariaSelected",
  "ariaSetsize",
  "ariaValuemax",
  "ariaValuemin",
  "ariaValuenow",
  
  "autocomplete",
  "blockDiraction",
  "canHaveChildren",
  "canHaveHTML",
  "hideFocus",
  "isContentEditable",
  "isDisabled",
  "isMultiLine",
  "isTextEdit",
  "language",
  "msBlockProgression",
  "msBoxSizing",
  "onOffBehavior",
  "outerHTML",
  "outerText",
  "parentTextEdit",
  "quotes",
  "role",
  "scopeName",
  "sourceIndex",
  "tagUrn",
  "uniqueID",
  
  "all", 
  "behaviorUrns",
  
  "onactivate",
  "onbeforeactivate",
  "onbeforecopy",
  "onbeforecut",
  "onbeforedeactivate",
  "onbeforeeditfocus",
  "onbeforepaste",
  "oncontextmenu",
  "oncopy",
  "oncut",  
  "ondeactivate",
  "ondrag",
  "ondragend",
  "ondragenter",
  "ondragleave",
  "ondragover",
  "onfocusin",
  "onfocusout",
  "onhelp",
  "onclosecapture",
  "onmouseenter",
  "onmouseleave",
  "onmove",
  "onmoveend",
  "onmovestart",
  "onpaste",
  "onpropertychange",
  "onreadystatechange",
  "onresizeend",
  "onresizestart",
  "onselectstart",
  "ontimeerror",
  
  // methods.
  "addBehavior",
  "applyElement",
  "attachEvent",
  "blur",
  "clearAttributes",
  "click",
  "componentFromPoint",
  "contains",
  "detachEvent",
  "dragDrop",
  "fireEvent",
  "focus",
  "getAdjacentText",
  "getExpression",
  "insertAdjacentElement",
  "insertAdjacentHTML",
  "insertAdjacentText",
  "item",
  "mergeAttributes",
  "namedItem",
  "querySelector",
  "querySelectorAll",
  "releaseCapture",
  "removeBehavior",
  "removeExpression",
  "removeNode",
  "replaceAdjacentText",
  "replaceNode",
  "setActive",
  "setCapture",
  "setExpression",
  "swapNode",
  "urns",
  
  // objects.
  "currentStyle",
  "runtimeStyle",

  // WF2.0
  "accept",
  "checkValidity",
  "replace",
  "data",
  "resetFromData",
  "dispatchFormInput",
  "dispatchFormChange",
  "templateElements",
  
  // Proprietary Moz/HTML 5
  "isDefaultNamespace",
  
  // Opera
  "childElementCount",
  "firstElementChild",
  "lastElementChild",
  "previousElementSibling",
  "repeatMin",
  "repeatStart",
  "repetitionBlocks",
  "repetitionIndex",
  "repetitionTemplate",
  "repetitionType",
  "repeatMax",
  "text",
  "unselectable",
  "addRepetitionBlock",
  "addRepetitionBlockByIndex",
  "moveRepetitionBlock",
  "removeRepetitionBlock",
  "selectNodes",
  "selectSingleNode",
  "addEventSource",
  "removeEventSource", 
  
  // Webkit
  "oninput",
  "scrollByLines",
  "scrollByPages",
  "document",
  "onsearch",
  "onunload",
  
  // Scope chain for event handler attributes.
  "window",
  
  // Object.prototype
  "constructor",
  "toString",
  "toLocaleString",
  "valueOf",
  "hasOwnProperty",
  "isPrototypeOf",
  "propertyIsEnumerable",
  "watch",
  "unwatch"
].sort();